functional:  
 -Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
 -Пользователь должен иметь возможность искать товары по ключевому слову или категории.
 -Пользователь должен иметь возможность фильтровать товар
 -Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 -Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
 -Сайт должен иметь мобильную версию.
 -Сайт должен быть способен обрабатывать большое количество трафика
 -Сайт должен быть доступен на различных устройствах
implicit:
 -при переходе на другой язык оформления сайта должен менятся язык  описания  товара на язык сайта 
 -Пользователь должен иметь расширенную возможность фильтровать товар
 -Сайт должен быть безопасным и защищать данные пользователя.
 -Сайт должен быть протестирован на совместимость с последними версиями браузеров.
